name: beurs
description: "A new Flutter project."

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  get: ^4.7.2
  flutter_screenutil: ^5.9.3
  get_storage: ^2.1.1
  google_fonts: ^6.2.1
  another_flushbar: ^1.12.30
  device_info_plus: ^11.3.2
  cached_network_image: ^3.4.1
  dartz: ^0.10.1 #pending
  connectivity_plus: 4.0.1
  image_picker: ^1.1.2
  flutter_rating_bar: ^4.0.1
  flutter_native_splash: ^2.4.5
  firebase_core: ^3.12.1
  firebase_messaging: ^15.2.4
  webview_flutter: ^4.10.0
  permission_handler: ^11.4.0
  flutter_local_notifications: ^18.0.1
  flutter_widget_from_html: ^0.16.0
  http: ^1.3.0
  firebase_auth: ^5.5.1
  animated_text_kit: ^4.2.3
  flutter_spinkit: ^5.2.1
  intl: ^0.20.2
  path_provider: ^2.1.5
  logger: ^2.5.0
  google_mobile_ads: ^5.3.1
  path: ^1.9.1
  flutter_contacts: ^1.1.9+2
  geolocator: ^13.0.2
  geocoding: ^3.0.0
  flutter_facebook_auth: ^7.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: frisky
      fonts:
        - asset: assets/fonts/frisky/FriskyPuppy.ttf